---
defaults:
  mail:
    gid: 5000
    homedir: /var/vmail
    maildir: /var/vmail/%d/%a
    uid: 5000
  web:
    allow_override: All
    ip_map:
      74.208.209.127: 5.9.35.102
      74.208.209.129: 5.9.35.102
    ruby: y
    suexec: y
    traffic_quota_lock: n
    stats_type: webalizer
server:
  mail: 5.9.28.24
  web: 5.9.35.102
  db:  5.9.35.102
plesk:
  db: psa
  host: 127.0.0.1
  port: 3306
  user: pleskuser
  pass: foo
  sync:
    host: dcs001.zonarix.com
    port: 12300
    user: mabet_zo_tec
ispconfig:
  uri: http://192.168.56.3:8079/remote/
  proxy: http://192.168.56.3:8079/remote/index.php
  user: apiuser
  pass: 123456
postscript: execute_me_later.sh
