---
defaults:
  mail:
    gid: 5000
    homedir: /var/vmail
    maildir: /var/vmail/%d/%a
    uid: 5000
  web:
    allow_override: All
    ip_map:
      74.208.209.127: 5.9.35.102
      74.208.209.129: 5.9.35.102
    ruby: y
    suexec: y
    traffic_quota_lock: n
server:
  mail: 5.9.28.24
  web: 5.9.35.102

